apiVersion: v1
kind: Pod
metadata:
  name: remote-host
  namespace: jenkins
  labels:
    app: remote-host
spec:
  containers:
    - image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/remote-host:1.2 
      name: remote-host
      ports:
        - containerPort: 22
      volumeMounts:
        - name: remote-host-script
          mountPath: "/home/jenkins/wp-data-files/avangels-db-backup-s3.sh"
          subPath: avangels-db-backup-s3.sh
  volumes:
    - name: remote-host-script
      persistentVolumeClaim:
            claimName: remote-host-pvc

  imagePullSecrets:
  - name: remote-secret

