apiVersion: v1
kind: PersistentVolume
metadata:
  name: remote-host-pv-tmp
#  namespace: jenkins
  namespace: remote-host
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  storageClassName: remote-host-pv
  hostPath:
#    path: "/var/efs/remote-host"
    path: "/home/jenkins/remote-host-data-files/tmp"
