apiVersion: v1
kind: Service
metadata:
  name: remote-host
  namespace: remote-host
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: remote-host
      port: 22
      targetPort: 22
  selector:
    app: remote-host
  clusterIP: 10.97.129.185
