apiVersion: v1
kind: Pod
metadata:
  name: remote-host
  namespace: jenkins
  labels:
    app: remote-host
spec:
  containers:
    - image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/remote-host:1.1 
      name: remote-host
      ports:
        - containerPort: 22
      volumeMounts:
        - name: remote-host-script
          mountPath: "/home/jenkins/wp-data-files/my-wp-db-backup-s3"
          subPath: my-wp-db-backup-s3.sh
        - name: remote-host-tmp
          mountPath: "/tmp"

  volumes:
    - name: remote-host-script
      persistentVolumeClaim:
            claimName: remote-host-pvc
    - name: remote-host-tmp
      persistentVolumeClaim:
            claimName: remote-host-pvc-tmp

  imagePullSecrets:
  - name: remote-secret

